name: flutter_fling
description: A simple flutter plugin to cast media to FireTv and FireStick.
version: 2.0.2
author: Suppa <vucuong19091997@gmail.com>
homepage: https://github.com/SuppaStrong/flutter_fling

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: dev.pharsh.flutter_fling
    pluginClass: FlutterFlingPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
